development:
  adapter: postgresql
  database: wine_app_lite
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: wine_app_lite_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: wine_app_lite_prod
  pool: 5
  timeout: 5000
